# Generated by Django 2.0.4 on 2018-04-25 14:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, null=True)),
            ],
            options={
                'db_table': 'categories',
            },
        ),
        migrations.CreateModel(
            name='ImageData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128, null=True)),
                ('short_description', models.CharField(max_length=128, null=True)),
                ('full_description', models.CharField(max_length=128, null=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('rating', models.IntegerField(null=True)),
                ('creative', models.BooleanField(default=False)),
                ('is_publish', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'image_data',
            },
        ),
        migrations.CreateModel(
            name='ImageFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(db_index=True, max_length=128, null=True)),
                ('original_name', models.CharField(max_length=128, null=True)),
                ('thumb_name', models.CharField(max_length=128, null=True)),
                ('preview_name', models.CharField(max_length=128, null=True)),
                ('added_date', models.DateTimeField(auto_now_add=True)),
                ('is_color', models.BooleanField(default=True)),
                ('orientation', models.CharField(max_length=128, null=True)),
                ('is_new', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'image_file',
            },
        ),
        migrations.CreateModel(
            name='ImageToCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administration.Category')),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administration.ImageFile')),
            ],
            options={
                'db_table': 'images_to_categories',
            },
        ),
        migrations.CreateModel(
            name='ImageToPlace',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administration.ImageFile')),
            ],
            options={
                'db_table': 'images_to_places',
            },
        ),
        migrations.CreateModel(
            name='ImageToTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administration.ImageFile')),
            ],
            options={
                'db_table': 'images_to_tags',
            },
        ),
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, null=True)),
            ],
            options={
                'db_table': 'places',
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, null=True)),
                ('weight', models.IntegerField(default=1)),
            ],
            options={
                'db_table': 'tags',
            },
        ),
        migrations.AddField(
            model_name='imagetotag',
            name='tag',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administration.Tag'),
        ),
        migrations.AddField(
            model_name='imagetoplace',
            name='place',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administration.Place'),
        ),
        migrations.AddField(
            model_name='imagedata',
            name='img_file',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administration.ImageFile'),
        ),
    ]