# Generated by Django 2.1 on 2018-08-20 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagedata',
            name='api_id',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True, unique=True),
        )
    ]
