# Generated by Django 2.1 on 2018-08-20 13:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0002_auto_20180820_1258'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imagetocategory',
            name='category',
        ),
        migrations.RemoveField(
            model_name='imagetocategory',
            name='image',
        ),
        migrations.RemoveField(
            model_name='imagetoplace',
            name='image',
        ),
        migrations.RemoveField(
            model_name='imagetoplace',
            name='place',
        ),
        migrations.RemoveField(
            model_name='imagetotag',
            name='image',
        ),
        migrations.RemoveField(
            model_name='imagetotag',
            name='tag',
        ),
        migrations.AddField(
            model_name='imagedata',
            name='categories',
            field=models.ManyToManyField(blank=True, null=True, to='administration.Category'),
        ),
        migrations.AddField(
            model_name='imagedata',
            name='place',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='administration.Place'),
        ),
        migrations.AddField(
            model_name='imagedata',
            name='tags',
            field=models.ManyToManyField(blank=True, null=True, to='administration.Tag'),
        ),
        migrations.DeleteModel(
            name='ImageToCategory',
        ),
        migrations.DeleteModel(
            name='ImageToPlace',
        ),
        migrations.DeleteModel(
            name='ImageToTag',
        ),
    ]
