# Generated by Django 2.1 on 2018-08-20 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0003_auto_20180820_1345'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imagedata',
            name='categories',
        ),
        migrations.AddField(
            model_name='imagedata',
            name='categories',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='imagedata',
            name='place',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.RemoveField(
            model_name='imagedata',
            name='tags',
        ),
        migrations.AddField(
            model_name='imagedata',
            name='tags',
            field=models.TextField(blank=True, null=True),
        ),
    ]
