# Generated by Django 2.1 on 2018-08-20 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0004_auto_20180820_1430'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagedata',
            name='day',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='imagedata',
            name='decennary_year',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='imagedata',
            name='is_decennary',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='imagedata',
            name='month',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='imagedata',
            name='year',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
