# Generated by Django 2.1 on 2018-08-22 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0005_auto_20180820_1504'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagedata',
            name='archive',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='imagedata',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='imagedata',
            name='status',
            field=models.CharField(choices=[('S', 'Publicato'), ('N', 'Non publicato')], default='S', max_length=1),
        ),
    ]
