# Generated by Django 2.1 on 2018-08-22 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0006_auto_20180822_1536'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagedata',
            name='scope',
            field=models.CharField(choices=[('S', 'Solo editoriale'), ('N', 'Editoriale e stampa')], default='S', max_length=1),
        ),
        migrations.AlterField(
            model_name='imagedata',
            name='status',
            field=models.CharField(choices=[('S', 'Publicato'), ('N', 'Non publicato')], default='N', max_length=1),
        ),
    ]
