# Generated by Django 2.1 on 2018-08-23 06:26

from django.db import migrations
import separatedvaluesfield.models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0007_auto_20180822_1545'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagedata',
            name='categories',
            field=separatedvaluesfield.models.SeparatedValuesField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='imagedata',
            name='tags',
            field=separatedvaluesfield.models.SeparatedValuesField(blank=True, max_length=255, null=True),
        ),
    ]
