# Generated by Django 2.1 on 2018-08-23 10:07

from django.db import migrations, models

def update_orientation(apps, schema_editor):
    ImageFile = apps.get_model('administration', 'ImageFile')
    orientation_choices = {
        'landscape': '1',
        'horizontal': '1',
        'vertical': '2',
        'square': '3',
        'panoramic': '4'
    }
    for image in ImageFile.objects.all():
        image.orientation = orientation_choices[image.orientation]
        image.save()


def update_color(apps, schema_editor):
    ImageFile = apps.get_model('administration', 'ImageFile')

    for image in ImageFile.objects.all():
        image.color = 'B/N' if not image.is_color else 'C'
        image.save()



class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0008_auto_20180823_0626'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagefile',
            name='color',
            field=models.CharField(choices=[('B/N', 'B/N'), ('C', 'Color')], default=True, max_length=10),
        ),
        migrations.RunPython(update_color),
        migrations.RemoveField(
            model_name='imagefile',
            name='is_color',
        ),
        migrations.RunPython(update_orientation),
        migrations.AlterField(
            model_name='imagefile',
            name='orientation',
            field=models.IntegerField(blank=True, choices=[(1, 'Horizontal'), (2, 'Vertical'), (3, 'Square'), (4, 'Panoramic')], null=True),
        ),
    ]
