# Generated by Django 2.1 on 2018-09-18 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0012_auto_20180913_1250'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagedata',
            name='is_completed',
            field=models.BooleanField(default=False),
        ),
    ]
