# Generated by Django 2.1 on 2018-09-21 09:59

from django.db import models, migrations


def reverse_color(apps, schema_editor):
    ImageFile = apps.get_model('administration', 'ImageFile')

    for image in ImageFile.objects.all():
        if image.color == 'COL':
            image.color = 'C'
        image.save()


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0013_imagedata_is_completed'),
    ]

    operations = [
        migrations.RunPython(reverse_color, lambda x,y: None),
        migrations.AlterField(
            model_name='imagedata',
            name='support',
            field=models.CharField(blank=True,
                                   choices=[(None, 'Choose support'), ('6x6', '6x6'), ('35mm', '35mm'), ('6x9', '6x9')],
                                   max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='imagefile',
            name='color',
            field=models.CharField(blank=True, choices=[('B/N', 'B/N'), ('C', 'Color')], max_length=10, null=True),
        ),
    ]
