# Generated by Django 2.1 on 2019-01-03 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0016_auto_20181120_1342'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagedata',
            name='shop_link',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
